
[frontend]
18.204.37.203 COURSE=Ansible DURATION=1.5hrs TRAINER=satyam ansible_user=ec2-user ansible_password=DevOps321
#34.228.64.21   COURSE=Variables DURATION=4hrs TRAINER=satyam ansible_user=ec2-user ansible_password=DevOps321

[local]
localhost 

[all]
18.204.37.203 ansible_user=ec2-user ansible_password=DevOps321

[all:vars]
COURSE=ansible
DURATION=120hrs
TRAINER=sai