---
- name: nmap install and run
  hosts: local
  become: yes
  tasks:
    - name: install nmap server
      ansible.builtin.package:
        name: nmap
        state: present
    - name: verify nmap installation
      ansible.builtin.command: nmap --version
      register: nmap_out

    - name: show nmap version
      ansible.builtin.debug:
        var: nmap_out.stdout_lines[0]

