---
- name: MySql install and run
  hosts: local
  become: yes
  tasks:
    - name: install MySql server
      ansible.builtin.package:
        name: MySql
        state: present
    - name: start MySql
      ansible.builtin.service:
        name: MySql
        state: started
        enabled: yes
