---
- name: nmap install and run
  hosts: local
  become: yes
  tasks:
    - name: install nmap server
      ansible.builtin.package:
        name: nmap
        state: present
    - name: start nmap
      ansible.builtin.service:
        name: nmap
        state: started
        enabled: yes
