---
- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: ansible
    DURATION: 120hrs
    TRAINER: satyam
  tasks:
    - name: print the couse information
      ansible.builtin.debug:
        msg: hi {{ COURSE }}, duration {{ DURATION }}, trainer is {{ TRAINER }}
- name: print the coures information again
  ansible.builtin.debug:
    msg: hi {{ COURSE }}, duration {{ DURATION }}, trainer is {{ TRAINER }}
