---
- name: variables from files
  hosts: local
  connection: local
  vars_files:
    - course.yml
  tasks:
    - name: print the course information
      ansible.bultin.debug:
        msg: "Hello i am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is: {{
          TRAINER }}"
