---
- name: variables from inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "hello i am learning {{ COURSE }}, duration {{ DURATION }}, trainer is {{ TRAINER }}"
      