---
- name: loops
  hosts: local
  connection: local
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: hello, {{ loop }}
      loop:
        - mohan
        - sai
        - mohini
