---
- name: funtions
  hosts: local
  connection: local
  vars:
    persons: "chinna,vinod,pspk,vivo"
  tasks:
    - name: check undefined variable
      ansible.builtin.debug:
        msg: "welcome, {{ persons | default('vinod') }}"
    - name: print names
      ansible.builtin.debug:
        msg: "Hello, {{ persons | split(',') }}"
    - name: convert map into list
      vars:
        course:
        name: ansible
        duration: 10HR
        trainer: satyam
      ansible.builtin.debug:
        msg: "Course Info: {{ course | dict2items  }}"
    - name: convert list into map
      vars:
        course:
        - key: name
          value: ansible
        - key: duration
          value: 10HR
        - key: trainer
          value: satyam
      ansible.builtin.debug:
        msg: "Course Info: {{ course | items2dict  }}"

